# App Name
name: flutterweb

# App Description
description: A new Flutter project.

# Remove this line if you wish to publish to pub.dev
publish_to: "none"

# App Version for both Android & iOS
version: 1.0.0+1

# Dart SDK Version
environment:
  sdk: ">=2.7.0 <3.0.0"

# App Packages from pub.dev for both debug & release mode & for both Android & iOS
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  service_worker: ^0.2.4
  provider: ^4.0.5
  firebase: ^7.3.0
  http: ^0.12.0+4
  firebase_core: ^0.4.4+3
  cloud_firestore: ^0.13.5
  shared_preferences: ^0.5.7
  page_transition: ^1.1.5

# App Packages from pub.dev only for debug mode for both Android & iOS
dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: any

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: opensans
      fonts:
        - asset: assets/fonts/OpenSans.ttf

    - family: raleway
      fonts:
        - asset: assets/fonts/Raleway-Black.ttf
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 700

    - family: robotocondensed
      fonts:
        - asset: assets/fonts/RobotoCondensed-Regular.ttf
        - asset: assets/fonts/RobotoCondensed-Bold.ttf
          weight: 700
